# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a499ebe4a5df43a72c1a3927be4ad1d991a355e0c47a5bed8cbb9c6669a8f73b3fa3806a71ef5fb23350493a151fbd6144316329287b51b3b840d2b103528119

test:
  secret_key_base: 3aac224c4a1484814a0afce66db5a8a91b769c4181a413ed025e78865eddf0d3fbcb78f3498fb7821538e13ddcfb12b10fdc24a0476a6f8477119a22541d78b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
